### ISSUE TITLE
Contact us page design

### ISSUE THREAD

**Issue by dwip708** [dwip708/EcoFusion#1]
Contact us page is not deigned. Need to design a proper contact us page for the website, with appropriate styling.

**Comment by TusharGupta-Developer** [comment]
Hi @dwip708 , I want to work on this issue. Assign me for it.

**Comment by dwip708** [comment]
Sure. Comment here / contact me at brahma.dwip.56@gmail.com for any problems. Just make a contact us page that will be in general helpful for any E-commerce platform in general.

**Comment by TusharGupta-Developer** [comment]
Subject: Hacktoberfest Participation

Hi ,

I saw that the repo isn't taking part in Hacktoberfest right now. My recent PR isn't being counted because of this.

Could you please add the "hacktoberfest" topic and label accepted PRs with "hacktoberfest-accepted"? This way, contributions will be recognized during the event.

Thanks a lot!

**Comment by TusharGupta-Developer** [comment]
That will be great help for me!

**Comment by dwip708** [comment]
Yes I have added the hacktoberfest label in the issue and also attached hacktoberfest-accepted label with the PR. I have followed all guidelines mentioned, for a repository to be considered as one participating in hacktoberfest.

I hope your PR gets counted soon. If not, please update me, and I shall look into it.

Thanks for your contribution,
Dwip Brahma.

**Comment by dwip708** [comment]
@TusharGupta-Developer did the PR count in hacktoberfest ?

**Comment by TusharGupta-Developer** [comment]
Yes, it counts in hacktoberfest.
Thanks!
